version: '3'

services:
  mysql:
    image: mysql:${IMG_MYSQL_VERSION}
    container_name: mysql-con-voc
    environment:
      MYSQL_ROOT_PASSWORD: ${_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${_MYSQL_DATABASE}
    volumes:
      - ${MYSQL_DATA_DIR}:/var/lib/mysql
    ports:
      - ${HOST_MYSQL_PORT}:3306
    restart: on-failure
    networks:
      - default_net

networks:
  default_net:
    driver: bridge
